# 应用名称
spring:
  application:
    name: recipe_spingboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/recipe?serverTimezone=UTC
# 应用服务 WEB 访问端口
server:
  port: 8888
#spring.datasource.name=defaultDataSource
# 数据库用户名&密码：



